[package]
name = "modality-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
num-bigint = "0.4.5"
num-traits = "0.2.19"
sha1 = "0.10.6"
sha2 = "0.10.8"
tokio = { version = "1", features = ["full"] }
